import { JSX, SVGProps } from "react"
import Image from "next/image"
import SearchPage from "./SearchPage"

/**
 * Generated by v0.
 * A banner for the AI Chat chrome extension.
 * @see https://v0.dev/t/SGV5W0siuOZ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
export default function Banner() {
  return (
    <div className="bg-[#0f0f0f] min-h-screen flex items-center justify-center text-white p-8">
      <div className="w-1/3 text-center">
        <div className="flex items-center justify-center mb-8">
          <img alt="logo" src="/logo.svg" className="h-10" />
          <h1 className="text-4xl font-bold mx-3">AI Chat</h1>
        </div>
        <h2 className="text-xl mb-4">Get Answers from ChatGPT on Search</h2>
        <div className="flex justify-center space-x-4 mb-12">
          <TriangleIcon className="text-white h-8 w-6" />
          <CloudIcon className="text-white h-8 w-8" />
          <WindIcon className="text-sky-400 h-8 w-8" />
        </div>
      </div>
      <div className="bg-gray-800 bg-opacity-50 rounded-lg m-6 p-6 w-2/3">
        <div className="flex justify-between mb-4">
          <div className="flex space-x-1">
            <div className="bg-red-500 rounded-full h-3 w-3" />
            <div className="bg-yellow-500 rounded-full h-3 w-3" />
            <div className="bg-green-500 rounded-full h-3 w-3" />
          </div>
          <ChevronDownIcon className="text-white h-5 w-5" />
        </div>
        <SearchPage />
      </div>
    </div>
  )
}

type IconProps = JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>

function ChevronDownIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function CloudIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z" />
    </svg>
  )
}


function ComponentIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5.5 8.5 9 12l-3.5 3.5L2 12l3.5-3.5Z" />
      <path d="m12 2 3.5 3.5L12 9 8.5 5.5 12 2Z" />
      <path d="M18.5 8.5 22 12l-3.5 3.5L15 12l3.5-3.5Z" />
      <path d="m12 15 3.5 3.5L12 22l-3.5-3.5L12 15Z" />
    </svg>
  )
}


function DotIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12.1" cy="12.1" r="1" />
    </svg>
  )
}

function TriangleIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z" />
    </svg>
  )
}


function WindIcon(props: IconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.7 7.7a2.5 2.5 0 1 1 1.8 4.3H2" />
      <path d="M9.6 4.6A2 2 0 1 1 11 8H2" />
      <path d="M12.6 19.4A2 2 0 1 0 14 16H2" />
    </svg>
  )
}
